[package]
name = "koi-gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
bytemuck = { version = "1.25.2", features = ["derive"] }
libc = "0.2"
pollster = "1.0.1"
wgpu = { version = "30.0.1", default-features = false, features = ["vulkan", "wgsl", "std"] }

[profile.release]
debug = false
