[package]
name = "koi-web"
description = "The koi pond in a web page, for site/"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
koi-render.workspace = true
koi-sim.workspace = true
koi-synth.workspace = true
koi-theme.workspace = true
wasm-bindgen = "0.2.129"
