[package]
name = "koi-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
bytemuck.workspace = true
koi-sim.workspace = true
koi-theme.workspace = true
pollster.workspace = true
wgpu.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
wgpu = { workspace = true, features = ["metal"] }

[target.'cfg(windows)'.dependencies]
wgpu = { workspace = true, features = ["dx12"] }
